.travis.yml
Unlike overflower, we don't need to distinguish between usize widths, so we can get rid of the build matrix. Also there should be no difference between debug and release builds, so we can get rid of that, too. This should speed up the build somewhat.
=> Simplify travis build

.gitignore, README.md, examples/example_project/src/lib.rs, runner/Cargo.toml, runner/src/main.rs
Not finished yet but wanted the put it out here early to get feedback. This should solve #2.
This runs cargo test for every mutation and checks if at least one test fails
The idea is to run `cargo install` in the runner dir then run `cargo test && cargo mutagen` in the example dir
TODO:
=> WIP Add mutagen test runner

runner/Cargo.toml, runner/src/main.rs
This parses the message output of `cargo test --no-run --message-format=json` to find out the location of the test binary to call it directly without the indirection through `cargo test`, which should be a bit faster.
I also added myself to the author list so I can publish cargo-mutagen on crates.io.
=> Change the runner to find and run the test binary directly

plugin/src/lib.rs
Easy one: labels of the mutations are not in sync with the code.
=> Fix mutation descriptions

plugin/src/lib.rs
When mutating code located on a module (so, any code which is not the one which has `extern crate mutagen;`), it fails to compile the code generated from the plug-in. It throws the following error:
```
|
164 |     #[cfg_attr(test, mutate)]
|                      ^^^^^^^ Use of undeclared type or module `mutagen`
```
To fix this issue, I have changed the macro expansions to reference the
mutagen functions from the root namespace.
=> Use root namespace on macro expansion

.gitignore, plugin/Cargo.toml, plugin/tests/compile-fail/failing_eq_ne.rs, plugin/tests/compile-fail/issue-34.rs, plugin/tests/compile-test.rs, plugin/tests/run-pass/test_eq_ne.rs
Adding compiletest library and adding an example for eq and ne mutations
that are applied properly.
Related to: https://github.com/llogiq/mutagen/issues/37
On the other hand, I'm adding some tests that currently are failing (on
the compile-fail folder) that we should fix at some time. I think it
may be useful to keep track of the issues pending to be fixed and it
will help to not add regressions of known patterns that caused issues on
the past.
@llogiq @hmvp I'm not sure about keeping track of the "compile-fail" tests. What do you think?
=> Add compiletest support

.gitignore, build.rs, plugin/src/lib.rs, plugin/tests/run-pass/failing_eq_ne.rs, plugin/tests/run-pass/issue-34.rs, src/lib.rs
This fixes #34 and removes unneeded closures for all operations. With the last commit, we also get a first step towards #21 and #12, among others. 
I also ran rustfmt over the plugin.
=> harden plugin

plugin/src/lib.rs
Until this PR, mutagen just ignored anything but plain ident patterns, so if you have `fn foo((a, b): (A, B))`, you were out of luck. This PR destructures all bindings and tries to keep as much information as possible.
=> orderly destructure patterns

plugin/src/lib.rs, plugin/tests/compile-fail/patterns.rs, plugin/tests/run-pass/patterns.rs
Match may have distinct types of patterns. When they are numeric or char
ranges, they need to be literals, but not expressions. If we do that mutation, we get the following error:
```
error[E0029]: only char and numeric types are allowed in range patterns
```
Now, when we detect a `Pat` which is of `PatKind::Range`, we are **not**
recursively mutating expressions. Otherwise, we are mutating as we were
doing before.
=>  Avoid mutate expressions on match Range patterns 

plugin/src/lib.rs, runner/src/runner.rs, src/coverage.rs
This is a thing I wanted to do for some time, and I finally got around to doing it :slightly_smiling_face:. The solution here is to first create a `static <genkey#N>: [AtomicUsize; 0]`, then do all the mutations, come back and patch up the length.
=> Change coverage flags to use a per-fn [AtomicUsize;_ ]

plugin/src/lib.rs, plugin/tests/run-pass/for_loops.rs, src/iterators.rs, src/lib.rs
Added a mutation for for-loops to mutate the iterator to the following
cases:
- Empty iterator (no elements will be yielded)
- Skip first element
- Skip last element
- Skip first and last element
=> Add mutation for iterators to skip elements

.travis.yml
Trying to run the plugin on the example project, with and without
coverage.
This should allow to avoid some regressions and make sure that we don't
break the runner.
=> Check runner on example project

runner/Cargo.toml, runner/src/main.rs, runner/src/runner.rs
Improve a little bit mutagen's runner:
- Added colors for better visibility.
- Remove tests output when tests are ok; as we count non-failing tests
as failure, the output was always the same: All tests green.
- Avoid saving the output of the test commands.
=> Improve runner output

plugin/src/lib.rs
Previously this was producing mutations like this, where the new variables go out of scope immediately and therefore have no effect.
```rust
if ::mutagen::now($n) {
let (a, b) = (b, a);
}
```
Now it produces this, which I think is a nice example of variable shadowing being useful:
```rust
let (a, b) = if ::mutagen::now($n) {
(b, a)
} else {
(a, b)
};
```
=> Fix mutation for interchangeables.

build.rs, plugin/src/lib.rs, plugin/tests/run-pass/clones.rs
This is one opportunistic mutation that was missing so far. It also moves coverage reporting into the trait impls so we only get reports for effective opportunistic mutations.
However, I run into the same problem as elsewhere when trying to report coverage in `fold_first_block`. Strange.
=> mutate ref muts by cloning

plugin/tests/compile-fail/may-clone-reserved.rs
A method of a struct which recives `&mut self` gets an error when
mutated.
This is because the `MayClone` mutation as the code generated is:
```rust
let self = if ::mutagen::MayClone::may_clone(self) {
_self_clone =
::mutagen::MayClone::clone(self, 2usize,
&__COVERAGE1[0usize], 2usize);
&mut _self_clone
} else {
self
};
```
This leads to initialize a variable with the name "self", which throws
this error: "expected unit struct/variant or constant, found local
variable `self` [E0424]"
=> Failing test for MayClone

plugin/src/lib.rs, plugin/tests/integration.rs
This fixes #103 
This makes both `Hash` and `PartialEq` implementations treat `self` and `_: Self` as equal, including putting them in the lifetime whitelist, because even if `Self` contains a lifetime, it's generally fixed and thus the same for all arguments.
While testing, I also noticed that putting `#[mutate]` on `impl` blocks didn't work, so I fixed that, too, while I was at it.
=> Make self / Self interchange work

runner/src/main.rs, runner/src/runner.rs
This also adds a `Status` type through which we can determine the reason for failure of a test run. It is not yet used for reporting though.
=> remove panics from runner

plugin/src/lib.rs, src/lib.rs
This closes #100 by adding opportunistic Default handling to both the helper library and the plugin, removing the former Default implementers whitelist and heuristic.
It also removes the `Letter` trait from the library, as it will not be useful any time soon.
=> Make `return Default` opportunistic

plugin/src/bounded_loop.rs, plugin/src/lib.rs
Change references from `to_ident` to `Ident::with_empty_ctxt()`, as it
seems that the former method does not exist anymore.
=> Fix nightly breakage

plugin/src/lib.rs
A new `NodeId` was added for impl traits. I don't know if it makes sense to check equality or hashing for node ids.
=> Fix rust update breakage

plugin/tests/run-pass/issue-127.rs, src/lib.rs
Tentatively fixes https://github.com/llogiq/mutagen/issues/127
When we call to `::mutagen::eq`, we are borrowing the left and right
values (so, we are `::mutagen::eq(&x, &y, ...)`. The previous
signature was also forcing a borrow `::mutagen::eq(x: &T, y: &R)`, which
provoked some type-inference issues as reported on:
https://github.com/llogiq/mutagen/issues/127.
=> Fix issue with references and type-inference

.travis.yml, Cargo.toml, examples/feature-gated/Cargo.toml, examples/feature-gated/src/lib.rs, mutagen-runner/Cargo.toml, mutagen-runner/src/main.rs
Fixes first part of #154.
This adds flags `--features` and `--all-features` to the runner in the same way cargo handles them.
=> add options to pass features in mutagen runner

.gitignore, mutagen-core/src/comm.rs, mutagen-core/src/comm/coverage.rs, mutagen-core/src/mutator/mutator_binop_bit.rs, mutagen-core/src/mutator/mutator_binop_num.rs, mutagen-core/src/mutator/mutator_stmt_call.rs, mutagen-core/src/mutator/mutator_unop_not.rs, mutagen-core/src/runtime_config.rs, mutagen-core/src/transformer.rs, mutagen-core/src/transformer/ast_inspect.rs, mutagen-core/src/transformer/transform_context.rs, mutagen-core/src/transformer/transform_info.rs, mutagen-runner/src/progress.rs, mutagen-runner/src/test_bin.rs, mutagen-selftest/src/mutator/test_binop_num.rs, mutagen-selftest/src/mutator/test_unop_not.rs
To be merged after #158.
I installed a spell checker on my IDE and found far more typos than I would have liked :see_no_evil: This PR fixes all typos I found.
=> Run spell check and fix typos

mutagen-runner/src/main.rs
cargo passes all args to the subcommand program, which means our binary will receive "mutagen" as first argument when invoked like this:
$ cargo mutagen
This produced an error, because structopt doesn't expect a "mutagen" argument at all:
error: Found argument 'mutagen' which wasn't expected, or isn't
valid in this context
USAGE:
cargo-mutagen [FLAGS] [OPTIONS]
For more information try --help
For a similar problem, see rust-lang/rustfmt#3569.
This is how they handle it: https://github.com/rust-lang/rustfmt/blob/9124dd88d6ef14d0ae77dc52ff5e9598f24a75a0/rustfmt-core/rustfmt-bin/src/cargo-fmt/main.rs#L77
I've opted for a simpler solution because I don't think `mutagen` could be one of the arguments for `cargo-mutagen` currently (naming an eventual feature `mutagen` doesn't seem right). If …
=> fix cargo-mutagen usage as cargo subcommand

README.md
This adds instructions on how to install the currently unreleased version of mutagen, along with a link to the released version on crates.io.
[fixes #159]
=> Update installation notes for unreleased version

mutagen-runner/src/main.rs
I have a project with multiple crates in a workspace, with only the "inner" one needing mutation testing. The data in `target/mutagen` was generated when I ran `cargo test --workspace`, but cargo-mutagen didn't detect it unless I also passed `--workspace` to the `cargo test` that cargo-mutagen runs, so I made this patch to add the argument.
---
Commits:
* This commit adds the `--package` and `--workspace` arguments to cargo-mutagen. They're implemented in the same way as the `--features` and `--all-features` arguments, getting passed through to the `cargo test` invocation.
=> Pass through --package and --workspace arguments

mutagen-core/Cargo.toml, mutagen-runner/Cargo.toml, mutagen-selftest/Cargo.toml, mutagen-transform/Cargo.toml, mutagen/Cargo.toml
This is a prerequisite to finally publishing mutagen-0.2; it's been waiting for far too long.
=> add license to Cargo.tomls

mutagen-core/Cargo.toml, mutagen-core/src/comm/mutagen_files.rs, mutagen-runner/Cargo.toml, mutagen-runner/src/main.rs, mutagen-runner/src/progress.rs, mutagen-runner/src/progress_bar.rs, mutagen-runner/src/test_bin.rs
This commit fixes #185 as mentioned in [Comparing Rust supply chain safety tools](https://blog.logrocket.com/comparing-rust-supply-chain-safety-tools/).
=> Replace deprecated failure crate with anyhow

docs/mutators.md, mutagen-core/src/mutator.rs, mutagen-core/src/mutator/mutator_lit_str.rs, mutagen-core/src/transformer.rs, mutagen-selftest/src/mutator.rs, mutagen-selftest/src/mutator/test_lit_str.rs, mutagen-selftest/src/test_not_mutated.rs
If you're open to new mutations, I created a mutator for string literals. It replaces empty strings with a single character string and for non-empty strings it does a few things: append and prepend a single character as well as replacing the string with an empty string. I'd welcome any feedback. Thanks!
=> Add str literal mutation
