llogiq/mutagen

- README.md
The most meta of all contributions
> Fix contributing link in Readme

- plugin/src/lib.rs
- src/lib.rs
> Fix issue #4: Use plain functions in helper lib

- Cargo.toml
- src/lib.rs
Fixes #15 
Let me know if i missed anything
> Allow to set mutation count using environment variable

- plugin/src/lib.rs
As suggested on https://github.com/llogiq/mutagen/issues/5, it would be
nice to mutate numeric constants adding or subtracting one unit to numeric constants.
At the moment, this is very conservative on the limits to add or
substract on default integer constants. I've did it like this to avoid
compilation issue, as we do not have information regarding the type of
the expression. So, in the default case, it subtracts one only if it's >
0 and it only adds one if the value is < 256.
If the constant has a type annotation (for example, 0i32), It adjust the
minimum and the maximum depending on the type hint. Note that it does
not check 128 bits numbers, as they are only available on nightly.
It chains the mutations in order to record only the needed
mutations. So, if the code finds a "0" on an …
> Add off-by-one mutation

- src/lib.rs
The code generated for eq and non-eq binary operations was not correct.
There was an issue with the generated code.
Previously, the expression generated on the macro, where wrapping the
expression on a closure, but the closure does not implement PartialEq,
which is needed to be able to compare for equality/non-equality.
The code has been changed to receive a boxed closure which returns a
PartialEq. This is the unique way I've found to make an easy example
compile.
> Fix eq and ne mutations 

- plugin/Cargo.toml
- plugin/tests/binops.rs
- src/lib.rs
Related to: https://github.com/llogiq/mutagen/pull/31
Blocks: https://github.com/llogiq/mutagen/pull/40
> Fix unequality operands

- plugin/src/lib.rs
- plugin/tests/binops.rs
Fix issue referenced in #40 and #32.
> Recursive mutation

- runner/src/main.rs
This allows us to e.g. compile with `--release` or `--features`.
> Pass through cargo test args from the runner

- plugin/src/lib.rs
This is PR for issue https://github.com/llogiq/mutagen/issues/16
> This closes #16

- runner/src/main.rs
This pull request partly resolves #55 since doctests can not work this way.
> support more than one executable

- build.rs
I'm going to try to refactor some more before I get the plugin to use the traits, but I wanted to introduce the corresponding assign ops first.
> add assign ops mutation traits

- runner/Cargo.toml
- runner/src/main.rs
> use failure for error handling

- plugin/src/lib.rs
This extends ArgTy to include the index in the argument list, and extends the hash function to follow the same invariants as our specialized `type_eq(..)`, which should make things faster and more stable.
> Use specialized hash function for args

- plugin/src/lib.rs
This splits a `Mutator` component from the `MutatorPlugin` that has everything that needs a mutable borrow. Also I simplify some code by factoring out common idioms.
> Refactor plugin for better borrowing & removing duplication

- .gitignore
- build.rs
- plugin/src/lib.rs
This should solve #70 and also add the missing mutations for #51, including op-assigns.
Closes #51
Closes #70
> fix atomic arrays, add all opportunistic mutations

- plugin/tests/compile-fail/many-mutations-same-scope.rs
> Failing test for #70

- plugin/src/lib.rs
- plugin/tests/integration.rs
> Improve grammar

- examples/example_project/src/lib.rs
- plugin/src/lib.rs
- runner/Cargo.toml
- runner/src/main.rs
- runner/src/runner.rs
- src/coverage.rs
- src/iterators.rs
This fixes #88 ...mostly. The timeout calculation is not configurable yet, but we can do this later.
I also added various improvements.
> first timeout impl (also various improvements)

- plugin/src/lib.rs
> extend to cope with other non-maximal consts

- runner/src/runner.rs
This removes the `Refcell<Option<Rc<_>>>` around `tests_with_mutations`, while keeping the borrow checker happy.
This fixes #102
> simplify runner

- plugin/src/lib.rs
- plugin/tests/run-pass/128-bit-types.rs
> support 128 bit types

- build.rs
- plugin/src/lib.rs
- plugin/tests/run-pass/test_eq_ne.rs
- src/lib.rs
Apply some clippy suggestions.
I'm not sure about the changes on: https://github.com/llogiq/mutagen/commit/fa40e2837b9233dc38da91535ea5c1a29456acfe  (I've got the feeling that it may cause issues with the borrow checker. Even that, I didn't found any issue with any mutated code).
> Apply some clippy suggestions

- plugin/src/bounded_loop.rs
- plugin/src/lib.rs
This contains a rustup that should get mutagen working again on current nightly.
> The Great Generics Generalization – mutagen edition

- plugin/src/lib.rs
We have a warning in our README, but I figure it cannot hurt to bail if we encounter any unsafe code.
> forbid mutating unsafe code

- plugin/src/lib.rs
> work around missing Hash and Eq impls

- README.md
- plugin/Cargo.toml
This is so I can publish an update to crates.io
> new plugin version

- README.md
- runner/src/main.rs
Some updates to the readme to include more warnings and update the usage (at least works on my machine). I hope the updated documentation is correct
>  update readme to include up-to-date suggestions and additional warnings

- README.md
closes #162. This PR fixes an incomplete sentence about the background functionality of mutagen.
> short paragraph about how mutagen works

- mutagen-core/Cargo.toml
- mutagen-core/src/comm/coverage.rs
- mutagen-core/src/comm/mutation.rs
- mutagen-core/src/comm/report.rs
- mutagen-core/src/mutator/mutator_binop_bit.rs
- mutagen-core/src/mutator/mutator_binop_bool.rs
- mutagen-core/src/mutator/mutator_binop_cmp.rs
- mutagen-core/src/mutator/mutator_binop_eq.rs
- mutagen-core/src/mutator/mutator_binop_num.rs
- mutagen-core/src/mutator/mutator_lit_bool.rs
- mutagen-core/src/mutator/mutator_lit_int.rs
- mutagen-core/src/mutator/mutator_stmt_call.rs
- mutagen-core/src/mutator/mutator_unop_not.rs
- mutagen-core/src/runtime_config.rs
- mutagen-core/src/transformer.rs
- mutagen-core/src/transformer/arg_ast.rs
- mutagen-core/src/transformer/mutate_args.rs
- mutagen-runner/Cargo.toml
- mutagen-runner/src/main.rs
- mutagen-runner/src/progress.rs
- mutagen-runner/src/progress_bar.rs
- mutagen-runner/src/test_bin.rs
- mutagen-transform/Cargo.toml
Thanks for making this proof of concept library! It's already useful. I noticed there are some clippy warnings, fixed them, and updated the dependencies, FWIW. Let me know what you think and if there is something else I can do here to get this merged.
> Fix clippy and update dependencies

- .github/workflows/main.yml
I implemented Github Action on the project.
Please let me know if something needs to be added
Thanks
> #182 Add Github Action
